# Generated by Django 4.1.6 on 2023-10-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_tag_tags_rename_unique_id_product_pro_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='filter_price',
            name='price_range',
            field=models.CharField(choices=[('1000 To 10000', '1000 To 10000'), ('10000 To 20000', '10000 To 20000'), ('20000 To 30000', '20000 To 30000'), ('30000 To 40000', '30000 To 40000'), ('40000 To 50000', '40000 To 50000'), ('50000 To 60000', '50000 To 60000'), ('60000 To 70000', '60000 To 70000'), ('70000 To 80000', '70000 To 80000'), ('80000 To 90000', '80000 To 90000'), ('90000 To 100000', '90000 To 100000'), ('100000 To 110000', '100000 To 110000'), ('110000 To 120000', '110000 To 120000'), ('120000 To 130000', '120000 To 130000'), ('130000 To 140000', '130000 To 140000'), ('140000 To 150000', '140000 To 150000'), ('150000 To above', '150000 To above')], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
